### PR TITLE
add copy-to-clipboard for token page

### PR DESCRIPTION
**Pull request by MnrGreg**
uses ClipboardJS to enable copy to clipboard functionality

addresses #4

works fine on windows clients

### CODE REVIEW

**Comment by nabadger** [comment]
Had a quick look - clipboard functionality works for me.

A couple of things:

1. Could we align the button to the right? `float:right` (I think). My CSS is terrible, but this is typically how I see this feature impl.
2. Could we maintain the formatting of the `kubectl` commands, mostly to make it easier to read.

For example:

```
kubectl config set-credentials kilgore-example-cluster-client-id \
  --auth-provider=oidc \
  --auth-provider-arg=idp-issuer-url=http://127.0.0.1:5556 \
  --auth-provider-arg=client-id=example-cluster-client-id \
```

...I don't mind doing these changes myself post-merge :)

Thanks again

**Comment by MnrGreg** [comment]
If we neaten up the formatting and include "\"s then the Copy/Paste for Windows clients will no loner work. This was the motivation behind adding the copy-to-clipboard.

Perhaps in future we could look at detecting the OS type from the User Agent string and then surface the different formatting schemes accordingly?

Added the resources to /static and set the button to the right.

**Comment by nabadger** [comment]
Ok, that makes sense. In terms of how you run `kubectl`, is it via using Powershell? If so, that's available for Linux/Mac now, so that might help me to check the commands work under windows as well.

**Comment by MnrGreg** [comment]
The use cases are PowerShell and standard CMD. Neither like the backslash as a line continuation. 

The Unix tools for Windows have both cat, curl and true but it would be great if we could implement some other alternative that doesn't require this.

**Comment by whereisaaron** [comment]
If we only have one version displayed then (sadly) I guess no continuation characters 😢 

Also, doing the formatting by Agent probably isn't the best. Many Windows users like myself will be copying from Chrome for Windows directly to bash on WSL 😄 So the user should have all the options available.

See #8 we planned to add a Windows/Powershell/Mac tabs to the HTML display. So we can use the correct continuation character on each tab (Windows CMD and Powershell use different characters). We could default the current tab based on the Agent, and people can switch if that is not what they need.

The other reason to have tabs (or similar) is so the certificate download command can have use the right tool, e.g. `curl` or `Invoke-WebRequest` and also link to the download for the correct `kubectl` binary.

**Comment by nabadger** [comment]
I still agree with the idea of having tabs per OS - that keeps things simple. 

I think this should get merged to master for now. I'll create a branch for #8 and give that a go over the weekend. Maybe we can end up having both features in the next release?

**Comment by whereisaaron** [comment]
That would be great @nabadger. We can do some simple tabs without any exotic dependencies.

https://www.w3schools.com/howto/howto_js_tabs.asp

**Comment by nabadger** [comment]
@MnrGreg may want to look at #33 

This splits the instructions for linux/mac and windows by introducing tabs,  which means we now have an opportunity to provide better windows specific instructions.

**Pull request merged**
