### PR TITLE
allow for base64 encoded k8s ca

### PR DESCRIPTION
**Pull request by jbonzo**
We found that when using templating tools its much easier to allow for base64 encoded CAs.

### CODE REVIEW

**Comment by jbonzo** [comment]
It seems that circleci is failing cause there is no circleci config present in this repo. Did I prepare this PR incorrectly or is there something else going on?

**Comment by nabadger** [comment]
> It seems that circleci is failing cause there is no circleci config present in this repo. Did I prepare this PR incorrectly or is there something else going on?

We replaced circle with github-actions - I've just found a leftover web-hook on the repo settings for circle which is now removed, so should have fixed it going forward (for now we can ignore the circle build error).

**Review by nabadger — COMMENTED** [review]
Would you mind adding this a configuration-option in the features docs?

https://github.com/mintel/dex-k8s-authenticator/blob/master/docs/config.md#configuration-options

Many thanks

**Comment by jbonzo** [comment]
> Would you mind adding this a configuration-option in the features docs?
> 
> https://github.com/mintel/dex-k8s-authenticator/blob/master/docs/config.md#configuration-options
> 
> Many thanks

Of course

**Review by nabadger — APPROVED** [review]

**Pull request merged**
